### ISSUE TITLE
merge and release Swift 3 branch

### ISSUE THREAD

**Issue by piemonte** [piemonte/Player#108]
merge and release Swift 3 branch

**Comment by Perjan** [comment]
Hey Patrick, after switching to Xcode 8 and updating to Swift 2.3 my app is crashing on this line:

`let timerange = (change?[NSKeyValueChangeNewKey] as! NSArray)[0].CMTimeRangeValue`

with the error message:
` *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'`

Can you please check it out?
Thanks a lot,
Perjan

**Comment by tsheaff** [comment]
@piemonte ETA on this?

**Comment by piemonte** [comment]
hey @tsheaff you should be able to point your podsfile to master or the repo + 0.2.0 tag.

i'll push to cocoapods itself soon, just waiting on some of the 1.1.0.rc.2 bugs to be fixed so that i can actually do so.

**Comment by piemonte** [comment]
[piemonte@jitensha(master)]$ pod trunk push Player.podspec 
Updating spec repo `master`
Validating podspec
 -> Player (0.2.0)

Updating spec repo `master`
  - Data URL: https://raw.githubusercontent.com/CocoaPods/Specs/f8541db78bc7ead57751d03aa768f922a50b252c/Specs/Player/0.2.0/Player.podspec.json
  - Log messages:
    - September 16th, 09:12: Push for `Player 0.2.0' initiated.
    - September 16th, 09:12: Push for `Player 0.2.0' has been pushed (0.379535509 s).
