### ISSUE TITLE
Add constraints to player view

### ISSUE THREAD

**Issue by chaocharleswang** [piemonte/Player#131]
I tried to add some constraints to player view, however, failed.

override func viewDidLoad()
{
        super.viewDidLoad()
        
        self.player.delegate = self
        
        self.addChildViewController(self.player)
        self.vPlayer.addSubview(self.player.view)
        self.vPlayer.sendSubview(toBack: self.player.view)
        self.player.didMove(toParentViewController: self)
        
        let leadConstraint = NSLayoutConstraint(item: self.vPlayer, attribute: .leading, relatedBy: .equal, toItem: self.player.view, attribute: .leading, multiplier: 1.0, constant: 0.0)
        let trailConstraint = NSLayoutConstraint(item: self.vPlayer, attribute: .trailing, relatedBy: .equal, toItem: self.player.playerView, attribute: .trailing, multiplier: 1.0, constant: 0.0)
        let topConstraint = NSLayoutConstraint(item: self.vPlayer, attribute: .top, relatedBy: .equal, toItem: self.player.view, attribute: .top, multiplier: 1.0, constant: 0.0)
        let bottomConstraint = NSLayoutConstraint(item: self.vPlayer, attribute: .bottom, relatedBy: .equal, toItem: self.player.view, attribute: .bottom, multiplier: 1.0, constant: 0.0)
        
        self.player.view.addConstraints([leadConstraint, trailConstraint, topConstraint, bottomConstraint])
        
        ...
}

Got error "libc++abi.dylib: terminating with uncaught exception of type NSException".

How can I solve the problem? Thanks!

**Comment by piemonte** [comment]
@chaocharleswang hey there, thanks for the interest in the library. you can set breakpoints in Xcode where exceptions are thrown and can also get exception details from the console. 

if you can print out those details and show the exception is caused by Player, we can get to the bottom of it. from a quick search, it looks like you just have a connection that's been changed:

http://stackoverflow.com/questions/26442414/libcabi-dylib-terminating-with-uncaught-exception-of-type-nsexception-lldb
