### ISSUE TITLE
Playing different videos with one Player

### ISSUE THREAD

**Issue by Jonovono** [piemonte/Player#3]
Hi. I couldn't use the player-swift tag on SO. Wondering if you have any idea how I should be doing this. My SO question is here:

http://stackoverflow.com/questions/27914846/photos-framework-connection-to-assetsd-was-interrupted-or-assetsd-died

Basically, I have this swipe view and depending on where you are in that it will either show an image or a certain video. 

I'm not sure where to create the Player() or how to properly remove it. When I create a new Player on every view I get a memory error. Creating one Player in viewWillAppear and changing the path when the swipe changes doesn't seem to work either.

Any thoughts?

Thanks :)

**Comment by piemonte** [comment]
hey @Jonovono apologies for the delay. my recommendation is to use one `Player` controller and then update it's URL path based on the necessary changes. i'm working on a method to allow the easy reset of a player with other folks. if it's a video, then display the view of the player, `player.view` otherwise your photo image view

:paperclip: https://github.com/piemonte/Player/issues/2#issuecomment-78549551
